apiVersion: batch/v1
kind: Job
metadata:
  name: test-cronjobasada
  namespace: zenith-beta
spec:
  template:
    spec:
      containers:
        - name: test-job-containeraasda
          image: darypte/mqtt-zenith:latest
          env:  # Agregar esta sección para definir variables de entorno
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_HOST
            value: "192.168.100.43"
          - name: RABBITMQ_USER
            value: "guest"
          - name: RABBITMQ_PASSWORD
            value: "guest"
          - name: RABBITMQ_PUBLISH_QUEUE
            value: "format/data"
          - name: RABBITMQ_CONSUMER_QUEUE
            value: ""
          - name: MYSQL_HOST 
            value: "192.168.100.43"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: "zenith"
          - name: MYSQL_PASSWORD
            value: "zenith"
          - name: MYSQL_DATABASE 
            value: "zenith"
          - name: ID_SENSOR 
            value: "7"
      restartPolicy: OnFailure