apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: zenith-beta
spec:
  schedule: "*/1 * * * *"  # Ejecuta cada minuto
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-job-container
            image: busybox  #
            command: ["echo", "Este es un CronJob de prueba."]
            env:  # Agregar esta sección para definir variables de entorno
            - name: MI_VARIABLE_ENTORNO
              value: "MiValor"
          restartPolicy: OnFailure